---
title: "Statistics for Business Analytics A-Z: Course Notes"
output:
  html_document:
    theme: lumen
    highlight: textmate
    fig_width: 6
    fig_height: 4
    toc: true
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("knitr")
```

# Introduction

This is a set of notes for the [Statistics for Business Analytics A-Z Course](https://www.udemy.com/data-statistics) on Udemy.

***

# Section 1
## Additional resources
- [Podcast episode - geospatial analytics](https://www.superdatascience.com/podcast-application-geospatial-analytics-business-real-life/)

***

# Section 2: Distributions

## Continuous vs Discrete
- Continuous variables can take any real value without any restrictions.
- Discrete variables can only take specific values.
- Example: foot size (continuous) vs shoe size (discrete)

## What is a distribution?
- A probability distribution is a mathematical function that can be thought of as providing the probability of occurrence of different possible outcomes in an experiment ([Wikipedia](https://en.wikipedia.org/wiki/Probability_distribution)).
- A distribution is a function linked to the underlying observations.
- A distribution provides the probability that an observation has a specific value.

### Visualizing distributions
- Discrete distributions are represented by bar charts, where the sum of all bar heights adds up to 1.
- Continuous distributions are visualized by a curve (probability density function). 
	  - The probability of an exact value (on the x axis) is 0, and there is an unlimited amount of numbers. 
	  - Probability is quantified as the area under the curve between two numbers: P(a < x b) = shaded area; calculated by integration. 
	  - The total area under the curve is 1.

## What is standard deviation?
- Variance is a measure of spread of the data about the mean: $$\sigma^2 = \frac{\Sigma_{i=1}^N(x_i - \mu)^2}{N}.$$ Variance is low when the spread of the data is low.
- Standard deviation is the square root of the variance. It is useful because it is defined in the same units as the original data and the mean.

## Normal distribution
- Defined by the probability density function $$p(x) = \frac{1}{\sigma\sqrt{2\pi}}e^{(-\frac{(x-\mu)^2}{2\sigma^2})}.$$
- For a normal distribution, the probability of an observation falling between the mean and 1 $\sigma$ away is 34.1%. Probability of falling between $-2\sigma$ and $+2\sigma$ is 95.4%.

## Skewness
- Distributions can be left (negative) skewed (longer tail on left) or right (positive) skewed (longer tail on right).
    - A left-skewed distribution has more outliers on the left.

## Mean, Median, Mode
- Include duplicates when calculating these statistics if duplicates are present in the data.
- For a right-skewed distribution, the median is to the right of the mean, and the mode is to the right of the median. To remember the order: the 3 statistics are in alphabetical order for a left-skewed distribution.
- The median is usually not affected by outliers as much as the mean.

***

# Section 3: Central Limit Theorem

## Populations & Samples
- A sample is a subset of the population.
- Parameters of a population: $N$ (number of observations in population), $\mu$ (mean), $\sigma$ (standard deviation).
    - Parameters are attributed to the whole population.
- Statistics of a sample: $n$ (number of observations in sample), $\bar{x}$ (sample mean), $s$ (sample standard deviation).
    - The statistics of a sample are used to assess the parameters of the population.

## Sampling Distribution
- Taking samples is not always useful, and should be solved with more advanced techniques. The sampling distribution is discussed here for this purpose.
- The sampling distribution is a set of samples of observations (e.g., each sample might have 10 observations, and there are a total of 20 such samples in the set). For each sample, take a mean. All the statistics make up the *sample distribution of the sample mean*.

## Central Limit Theorem
- Said to be one of the most important theorems in math and statistics.
- CLT states that given enough samples, the sample distribution of the sample mean looks like a normal distribution, regardless of the distribution of the original population.

## Central Limit Theorem - Intuition
- The mean of the sampling distribution of the sample mean equals the mean of the original distribution: $\mu_{\bar{x}} = \mu$. The sample means are distributed around the mean of the original distribution.
    - This is useful because the true mean of the population is not known.
- The standard deviation of the sampling distribution is related to the standard deviation of the population: $\sigma_{\bar{x}} = \frac{\sigma}{\sqrt{n}}$, where $\sigma$ is the standard deviation of the original population and $n$ the number of observations in each sample.

## Central Limit Theorem - Visualization
- Visualize CLT at [onlinestatbook.com](http://onlinestatbook.com/stat_sim/sampling_dist/index.html).
- The sample distribution gets closer to normal when $n$ is large.


## Z-Score (aka Standard Score, Normal Score, Normalized Variable)
- Percentage of observations between standard deviations: -1 to 1: 68.2%, -2 to 2: 95.4%, -3 to 3: 99.8%.
- Z-score is defined as $Z = \frac{x-\mu}{\sigma}$. It is the amount of standard deviations that a point $x$ is away from the mean $\mu$.
- Applied to all values, this procedure transforms the data to have $\mu=0$ and $\sigma=1$. A distribution with such mean and standard deviation is said to be normalized.
- Standard normal probability tables can be used to find probabilities.

## Hands-On CLT - Analytics Challenge

### Challenge

- You are a Business Analyst working for FedEx.
- A business client has requested a large freight to be transported urgently from Denver to Salt Lake City. When asked about the weight of the cargo they could not supply the exact weight, however they have specified that there are a total of 36 boxes. 
- From prior experience with this client you know that this type of cargo follows a distribution with a mean of $\mu$ = 72lb (32.66kg) and a std. dev. of $\sigma$ = 3lb (1.36kg).
- The only plane you currently have at Denver is a *Cessna 208B Grand Caravan* with a max cargo weight of 2630lb (1193kg).
- Based on this information what is the probability that all of the cargo can be safely loaded onto the plane and transported?

### Solution
- We know that the population parameters are $\mu$ = 72 and $\sigma$ = 3, but we don't know what the distribution looks like (most likely, the distribution is not normal).
- We know that the sampling distribution of the sample mean looks like a normal distribution. We also know that the mean of this sampling distribution is the same as $\mu$, and standard deviation of the sampling distribution is $\sigma/sqrt{n}$, where $n$=36.
- The plane capacity is 2640lb, so the critical mass for each box is $x_{crit} = \frac{2640lb}{36 boxes} = 73.06 lb/box$. This amount is to the left of the sample mean $\mu_{\bar{x}}.
- Calculate how far $x_{crit}$ is from $\mu$: $z = \frac{x_{crit} - \mu_{bar{x}}}{\sigma_{\bar{x}}} = \frac{73.06-72}{0.5}=2.12$.
- Find 2.12 in a z-score probability table: $P(x < x_{crit}) = 0.9830 = 98.3%$.
- Therefore, the probability that the cargo can be safely loaded onto the plane is 98.3%.

# Section 4: Hypothesis Testing

## Hypothesis Testing Steps
- Challenge: In 2015, millenials were watching 26.5 hours of TV a week with a $\sigma$ of 10 hours. Today you surveyed 50 millenials and found that they watch 24 hours of TV per week. Has the parameter decreased?
- Steps:
	- State the null hypothesis - $H_0$: the parameter has not decreased, i.e. $\mu \geq 26.5$.
	- State the alternative hypothesis - $H_1$: the parameter has decreased, i.e. $\mu < 26.5$.
		- Note: if we reject $H_0$, we can't say that the average is 24 hours. We can only say that the average has decreased.
	- Apply the concepts from CLT:
		- $\mu_{\bar{x}} = \mu = 26.5$.
		- $\sigma_{\bar{x}} = \frac{\sigma}{\sqrt{n}}$ = \frac{10}{\sqrt{50}} = 1.41$.
		- $\bar{x} = 24$.
	- Ask the question: how likely that we just randomly picked a sample of 50 millenials with a sample mean $\bar{x}$ that is so far away from the sample mean? Put another way: assuming that $H_0$ is true, how likely is it that we picked $\bar{x}$ at random?
	- Calculate the z-score: $z = \frac{24 - 26.5}{1.41} = -1.77$. 
	- So the p-value is $P = 0.0384 = 3.84%$ (found in probability table).
		- This is interpreted as: the probability of picking $\bar{x} to be 24 or less is 3.84%.
		- This value is less than 5%, so with 95% confidence, we reject the null hypothesis. We accept $H_1$, that the parameter is less than 26.5.


## Statistical Significance - Intuition
- Coin toss example: determine if a coin is fair or not.
	- $H_0$: this is a fair coin.
	- $H_1$: this is not a fair coin.
	- Assume that the coin is fair, and that each consecutive flip is returning tails. In this case, the p-value for tails in one toss is 0.5. The p-value for 2 consecutive tails is (0.5)(0.5) = 0.25. The p-value decreases with each toss.
	- If we knew that the coin is not fair, and keep getting consecutive tails, the p-value will not decrease as above.
	- Set the cutoff at $\alpha$ = 0.05. Once p-value is below $\alpha$, reject $H_0$ with 95% confidence.
		- $\alpha$ can be set to any value. E.g., 0.01 for medical applications.

## Hypothesis Testing - Rejection Region
- (Using same TV example from above)
- This is an alternative way of seeing hypothesis testing.
- Find $z_crit$ (in a probability table) such that there is a 5% chance of the event falling to the left of z on the pdf (if $\bar{x}$ is less than the mean): $z_crit$ = -1.65.
- The area to the left of $z_crit$ is the *rejection region*. The likelihood of randomly picking a sample from the rejection region is 5% or less. If the calculated $z$ is in this region, can reject $H_0$.
- This approach allows to set a confidence threshold (e.g., 95%) instead of having to look up z exactly in the probability table each time.

## Hypothesis Testing Assumptions
- Z-test assumptions:
	- 1. Sample is selected at random.
		- This assumption must hold throughout the entire experiment.
		- Simply increasing the sample size does not necessarily remove bias.
		- Example - for a phone survey conducted by calling phone numbers from a phone book, this will be biased towards people that still have a landline.
	- 2. Observations are independent.
		- Example: surveying the people in a room. If a person overhears others' examples, there might be peer pressure to respond similarly.
	- 3. Population standard deviation is known, OR the sample contains at least 30 observations (use t-test if <30).

## Proportion Testing
- Challenge: According to a 2016 survey, *"a staggering 58% of American households have tablets."* Your manager has asked you to test the Hypothesis (with a 97% significance level) that only 58% of American homes have tablet devices. You surveyed 100 random households and found that 73 of them had tablets.
- $H_0$: 58% or fewer of households have tablets, i.e. $p \leq 58%$.
- $H_1$: more than 58% have tablets, i.e. $p > 58%$.
	- $p$ is proportion.
- Perform two checks for proportion test:
	- 1. Check that $n\bar{p}$ > 10.
		- In example, $\bar{p}$ = 73/100, $n$ = 100.
	- 2. Check that $n\bar{q}$ > 10$.
		- $\bar{q} = \bar{p}-1$
		- In example, $\bar{q} in example is 0.27.
	- In the sample, the number of positive and negative observations both have to be greater than 10. If condition is not met, increase the sample size.
- New formulas (not derived here):
	- $\mu = p$
	- $\sigma = \sqrt{pq}$
- Calculations:
	- $\mu_{\bar{p}} = \mu = p = 0.58$ (from CLT)
	- $\sigma = \sqrt{pq} = \sqrt{(0.58)(0.42)} = 0.49$ (This assumes that $H_0$ is correct to be able to use p=0.58)
	- $\sigma_{\bar{p}} = \frac{\sigma}{\sqrt{n}}$ (from CLT)
	- $\bar{p} = 73/100 = 0.73$ (given in problem)
	- $z = \frac{\bar{p}-\mu_{\bar{p}}}{\sigma_{\bar{p}}} = \frac{0.73-0.58}{0.049} = 3.06$
	- p-value = 1 - 0.9989 = 0.11% < 3%
- Therefore, we can reject $H_0$ with >97% confidence and accept $H_1$.

## Homework Challenge
### Question
- You are a consultant engaged by a factory which manufactures spoons.
- The factory executives recently spent $10MM upgrading equipment and processes in order to combat excessively high defects in manufacturing (23%) which were leading to high return rates from clients.
- You have been asked to prove (with a confidence level of 95%) that new equipment has improved the situation and that the number of defective spoons has decreased to under 18%. You have been supplied with a random sample of 150 spoons and found that 23 spoons have defects.


### Solution
- $H_0$: 18% or more have defects, i.e. $p \geq 18%$.
- $H_1$: The number of defective spoons has decreased to under 18%.
- Calculations:
	- $\mu_{\bar{p}} = \mu = p = 0.23$ (from CLT)
	- $\sigma = \sqrt{pq} = \sqrt{(0.23)(0.77)} = 0.42$ (This assumes that $H_0$ is correct to be able to use p=0.23)
	- $\sigma_{\bar{p}} = \frac{\sigma}{\sqrt{n}} = 0.0343$ (from CLT)
	- $\bar{p} = 18/150 = 0.12$ (given in problem)
	- $z = \frac{\bar{p}-\mu_{\bar{p}}}{\sigma_{\bar{p}}} = \frac{0.12-0.23}{0.0343} = -3.207$
	- p-value = 1 - 0.9993 = 0.07% < 5%
